insert into whitelist_users (email, name, role, status)
values
  ('fe.fake.member001@example.com', 'FE Fake Member 001', 'Member', 'Active'),
  ('fe.fake.member002@example.com', 'FE Fake Member 002', 'Member', 'Active'),
  ('fe.fake.member003@example.com', 'FE Fake Member 003', 'Member', 'Active'),
  ('fe.fake.member004@example.com', 'FE Fake Member 004', 'Member', 'Active'),
  ('fe.fake.member005@example.com', 'FE Fake Member 005', 'Member', 'Active'),
  ('fe.fake.member006@example.com', 'FE Fake Member 006', 'Member', 'Active'),
  ('fe.fake.member007@example.com', 'FE Fake Member 007', 'Member', 'Active'),
  ('fe.fake.member008@example.com', 'FE Fake Member 008', 'Member', 'Active'),
  ('fe.fake.member009@example.com', 'FE Fake Member 009', 'Member', 'Active'),
  ('fe.fake.member010@example.com', 'FE Fake Member 010', 'Member', 'Active'),
  ('fe.fake.member011@example.com', 'FE Fake Member 011', 'Member', 'Active'),
  ('fe.fake.member012@example.com', 'FE Fake Member 012', 'Member', 'Active'),
  ('fe.fake.member013@example.com', 'FE Fake Member 013', 'Member', 'Active'),
  ('fe.fake.member014@example.com', 'FE Fake Member 014', 'Member', 'Active'),
  ('fe.fake.member015@example.com', 'FE Fake Member 015', 'Member', 'Active'),
  ('fe.fake.member016@example.com', 'FE Fake Member 016', 'Member', 'Active'),
  ('fe.fake.member017@example.com', 'FE Fake Member 017', 'Member', 'Active'),
  ('fe.fake.member018@example.com', 'FE Fake Member 018', 'Member', 'Active'),
  ('fe.fake.member019@example.com', 'FE Fake Member 019', 'Member', 'Active'),
  ('fe.fake.member020@example.com', 'FE Fake Member 020', 'Member', 'Active'),
  ('fe.fake.member021@example.com', 'FE Fake Member 021', 'Member', 'Active'),
  ('fe.fake.member022@example.com', 'FE Fake Member 022', 'Member', 'Active'),
  ('fe.fake.member023@example.com', 'FE Fake Member 023', 'Member', 'Active'),
  ('fe.fake.member024@example.com', 'FE Fake Member 024', 'Member', 'Active'),
  ('fe.fake.member025@example.com', 'FE Fake Member 025', 'Member', 'Active'),
  ('fe.fake.member026@example.com', 'FE Fake Member 026', 'Member', 'Active'),
  ('fe.fake.member027@example.com', 'FE Fake Member 027', 'Member', 'Active'),
  ('fe.fake.member028@example.com', 'FE Fake Member 028', 'Member', 'Active'),
  ('fe.fake.member029@example.com', 'FE Fake Member 029', 'Member', 'Active'),
  ('fe.fake.member030@example.com', 'FE Fake Member 030', 'Member', 'Active'),
  ('fe.fake.member031@example.com', 'FE Fake Member 031', 'Member', 'Active'),
  ('fe.fake.member032@example.com', 'FE Fake Member 032', 'Member', 'Active'),
  ('fe.fake.member033@example.com', 'FE Fake Member 033', 'Member', 'Active'),
  ('fe.fake.member034@example.com', 'FE Fake Member 034', 'Member', 'Active'),
  ('fe.fake.member035@example.com', 'FE Fake Member 035', 'Member', 'Active'),
  ('fe.fake.member036@example.com', 'FE Fake Member 036', 'Member', 'Active'),
  ('fe.fake.member037@example.com', 'FE Fake Member 037', 'Member', 'Active'),
  ('fe.fake.member038@example.com', 'FE Fake Member 038', 'Member', 'Active'),
  ('fe.fake.member039@example.com', 'FE Fake Member 039', 'Member', 'Active'),
  ('fe.fake.member040@example.com', 'FE Fake Member 040', 'Member', 'Active'),
  ('fe.fake.member041@example.com', 'FE Fake Member 041', 'Member', 'Active'),
  ('fe.fake.member042@example.com', 'FE Fake Member 042', 'Member', 'Active'),
  ('fe.fake.member043@example.com', 'FE Fake Member 043', 'Member', 'Active'),
  ('fe.fake.member044@example.com', 'FE Fake Member 044', 'Member', 'Active'),
  ('fe.fake.member045@example.com', 'FE Fake Member 045', 'Member', 'Active'),
  ('fe.fake.member046@example.com', 'FE Fake Member 046', 'Member', 'Active'),
  ('fe.fake.member047@example.com', 'FE Fake Member 047', 'Member', 'Active'),
  ('fe.fake.member048@example.com', 'FE Fake Member 048', 'Member', 'Active'),
  ('fe.fake.member049@example.com', 'FE Fake Member 049', 'Member', 'Active'),
  ('fe.fake.member050@example.com', 'FE Fake Member 050', 'Member', 'Active')
on conflict (email) do update
set
  name = excluded.name,
  role = excluded.role,
  status = excluded.status,
  updated_at = now();

